# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfcTCh1GmBeg1B4suHeCCoA8tawe7XNN
"""

# 1. Install library yang dibutuhkan (jika belum terinstall)
!pip install openpyxl scikit-learn pandas matplotlib seaborn

# 2. Import library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# 3. Upload file dari lokal
from google.colab import files
uploaded = files.upload()

# 4. Baca file Excel
df = pd.read_excel(next(iter(uploaded)), sheet_name=0)

# 5. Transformasi ke long format
df_long = df.melt(
    id_vars=["Provinsi", "Kabupaten Kota", "Nama Pasar", "Nama Variant"],
    var_name="Tanggal",
    value_name="Harga"
)

# 6. Ubah kolom tanggal jadi datetime & hapus yang gagal
df_long["Tanggal"] = pd.to_datetime(df_long["Tanggal"], errors='coerce', dayfirst=True)
df_long = df_long.dropna(subset=["Tanggal"])

# 7. Hapus baris harga kosong
df_clean = df_long.dropna(subset=["Harga"])

# 8. Fitur waktu
df_clean["day"] = df_clean["Tanggal"].dt.day
df_clean["month"] = df_clean["Tanggal"].dt.month
df_clean["dayofweek"] = df_clean["Tanggal"].dt.dayofweek

# 9. Label Encoding
le_dict = {}
for col in ["Provinsi", "Kabupaten Kota", "Nama Pasar", "Nama Variant"]:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col])
    le_dict[col] = le  # Simpan encoder

# 10. Pisah fitur dan target
X = df_clean[["Provinsi", "Kabupaten Kota", "Nama Pasar", "Nama Variant", "day", "month", "dayofweek"]]
y = df_clean["Harga"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 11. Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# 12. Random Forest
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# 13. Evaluasi
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

# 14. Print hasil
print("=== Linear Regression ===")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R² Score: {r2_lr:.4f}")

print("\n=== Random Forest ===")
print(f"RMSE: {rmse_rf:.2f}")
print(f"R² Score: {r2_rf:.4f}")

# 15. Plot perbandingan hasil
plt.figure(figsize=(10,5))
sns.scatterplot(x=y_test, y=y_pred_rf, alpha=0.3)
plt.xlabel("Harga Sebenarnya")
plt.ylabel("Harga Prediksi (Random Forest)")
plt.title("Prediksi Harga vs Asli")
plt.grid(True)
plt.show()

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

# Hitung metrik akurasi tambahan
mae = mean_absolute_error(y_test, y_pred_rf)
mape = mean_absolute_percentage_error(y_test, y_pred_rf) * 100

print("\n=== Evaluasi Akurasi Random Forest ===")
print(f"RMSE: {rmse_rf:.2f}")
print(f"R² Score: {r2_rf:.4f}")
print(f"MAE: {mae:.2f}")
print(f"MAPE: {mape:.2f}%")

# Tampilkan 10 sampel prediksi vs asli
hasil_df = pd.DataFrame({
    'Harga Asli': y_test.values,
    'Prediksi': y_pred_rf
})
hasil_df['Selisih'] = hasil_df['Prediksi'] - hasil_df['Harga Asli']
print("\nContoh Prediksi vs Harga Asli:")
print(hasil_df.head(10))

print("Jumlah harga = 0 dalam y_test:", (y_test == 0).sum())
print("Harga minimum dalam y_test:", y_test.min())

# Filter hanya yang harga aslinya bukan nol
mask = y_test != 0
mape = mean_absolute_percentage_error(y_test[mask], y_pred_rf[mask]) * 100
print(f"MAPE (tanpa nol): {mape:.2f}%")

import joblib

# Simpan model Random Forest
joblib.dump(rf, 'model_rf_harga.pkl')
print("✅ Model Random Forest berhasil disimpan sebagai 'model_rf_harga.pkl'")

